### ISSUE TITLE
Not grabbing Title/Not found when adding, but correct Manga in description/link

### ISSUE THREAD

**Issue by LilPeen** [tommyryan2002/Ruka-Bot#2]
Hi! Loving this tool btw, but running into issues with certain manga amongst peers.. atleast for myself the example I can give is:
Dont toy with me Nagatoro/Ijiranaide, Nagatoro-san. cant seem to add it to my list.. and when I search it on its own.. it comes up with "Manga Not Found" though the link and metadata is correct.

I've attached an example, not a deal breaker just figured I'd report it:

![image](https://user-images.githubusercontent.com/28698016/131545651-bf6a5a26-aa64-4266-ba3d-f4835bde2c2b.png)

I also tried by Mangadex link it provided, no luck. 

![image](https://user-images.githubusercontent.com/28698016/131545760-756c15d7-b02d-4aa1-a1a3-29b3201ad04b.png)

Hope this helps us both :D

**Comment by tommyryan2002** [comment]
Hey, thanks for reporting this. After some investigating, what was causing this issue was me hardcoding the function that grabs the "real" title from a search string to be labeled as "en", rather than just grabbing the one that was available. Because Nagatoro had its title labeled as "jp" it was unable to find the "real" title. This is why it would still return information about the manga but prevented you from tracking it. Mangalerts will likely be offline for the next 30 mins while I push and deploy the bug fix. Thanks again for bringing this to my attention, and if you still cant track any other titles let me know.

**Comment by LilPeen** [comment]
Hey, it worked great when I did the JP name. but a heads up.. when i tried to add the english name it just added something completely different. 

![image](https://user-images.githubusercontent.com/28698016/131899081-f06eb45c-bb29-4d54-a6a1-bffa5e4af169.png)

It works with the JP name though. 

![image](https://user-images.githubusercontent.com/28698016/131899114-f525c0cc-3e18-4bfe-820a-b0a1716804e3.png)

Again, thanks for the speedy fix. just wanted to give a heads up to maybe add a tooltip if a fix for the english name when one doesn't exist can't be done.

**Comment by tommyryan2002** [comment]
Yeah this one is a weird one. What's causing this is not actually an issue with my code seemingly, but a bug on the part of MangaDex. For some reason that specific search string returns a completely unrelated title. ![sc](https://i.imgur.com/Ssy6eK3.png) Really not sure why that happens but it's kinda out of my hands since Mangalerts assumes that the first related search is the one users are looking for. According to one of the MangaDex devs:
![sc2](https://i.imgur.com/PWVBRyV.png)
So until they fix it, just expect a few weird issues with the search tool. But again thanks for letting me know.

**Comment by tommyryan2002** [comment]
After looking at this a bit more it is also causing some issue with alerts as well 😭. I've been getting my own "phantom" alerts on a few titles that weren't actually updated. But, this should all be solved soon once MangaDex fixes their search tool🤞. Until then please just bare with a couple of bugs.

**Comment by tommyryan2002** [comment]
Looks like MangaDex has solved their issue, closing this issue for now!
